export const GET_DATOS_PERSONALES = "GET_DATOS_PERSONALES";
export const GET_HABILIDADES = "GET_HABILIDADES";
export const GET_ESTUDIOS = "GET_ESTUDIOS";
export const GET_CURSOS = "GET_CURSOS";
export const GET_EXPERIENCIA = "GET_EXPERIENCIA";
export const GET_REPOSITORIOS = "GET_REPOSITORIOS";
